name: Deploy HTTPie CLI

on:
  push:
    branches:
      - main  # Deploy whenever there's a push to the main branch
  workflow_dispatch:  # Allow manual deployment trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t httpie-cli:latest .

      # Step 4: Deploy the Docker container (local test or remote)
      - name: Run Docker container
        run: docker run --rm httpie-cli

      # Optional Step 5: Push the image to Docker Hub (for production)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker tag httpie-cli:latest <your-docker-hub-repo>/httpie-cli:latest &&
             docker push <your-docker-hub-repo>/httpie-cli:latest
